spring.application.name=vaultaire
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultaire
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

minio.url=http://localhost:9000
minio.access-key=minio
minio.secret-key=minio123
minio.bucket=vaultaire