services:
  - type: web
    name: vaultaire
    plan: free
    dockerComposePath: ./docker-compose.yml
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:5432/vaultaire
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: admin123
      - key: MINIO_URL
        value: http://minio:9000
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        value: minio123
      - key: MINIO_BUCKET
        value: vaultaire